# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGODB_DB_NAME: todo
      MONGODB_URI: mongodb://mongodb:27017
      JWT_SECRET: G1qxM@LOr$PkyKR6#F$Ta0B8vLr*UZvU #Recommend change to other self own JWT Secret Key
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
